### ISSUE TITLE
"Invalid tree found"-error in ember-cli 0.2.0 project

### ISSUE THREAD

**Issue by dennismende** [kellyselden/broccoli-jscs#19]
I added broccoli-jscs to an ember-cli 0.2.0 project and got the following error:

    Invalid tree found. You must supply a path or an object with a `read` function: undefined
    Error: Invalid tree found. You must supply a path or an object with a `read` function: undefined
        at readAndReturnNodeFor (/Users/dennis/Sites/flec-frontend/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:72:13)
    at /Users/dennis/Sites/flec-frontend/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:93:24
    at lib$rsvp$$internal$$tryCatch (/Users/dennis/Sites/flec-frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/dennis/Sites/flec-frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at /Users/dennis/Sites/flec-frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1095:13
    at lib$rsvp$asap$$flush (/Users/dennis/Sites/flec-frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)

**Comment by kellyselden** [comment]
The addon needs a `.jscsrc` file. Run:
```
echo {"esnext": true}>.jscsrc
```
in your app folder. I will open an issue to make this process clearer/cleaner.

**Comment by dennismende** [comment]
I tried that but it does not work. Same error as before. I added a .jscsrc file to the project directory but that didn't work. Then I tried it with a .jscsrc file within the app folder. The result was the same error.

**Comment by e1262667** [comment]
Did the `.jscsrc` file have any content? I created a new ember-cli@0.2.0 project with broccoli-jscs and got your error. Then I ran the command above, and the error went away.

**Comment by kellyselden** [comment]
Did the .jscsrc file have any content? I created a new ember-cli@0.2.0 project with broccoli-jscs and got your error. Then I ran the command above, and the error went away.

**Comment by dennismende** [comment]
Thank you very much for your support. I had a configuration error within jscsOptions. Everything works fine now.
