### ISSUE TITLE
Mocha Support

### ISSUE THREAD

**Issue by drewchandler** [kellyselden/broccoli-jscs#27]
Right now to get test generation to work with Mocha I am doing the following:
```javascript
var app = new EmberApp({
  jscsOptions: {
    enabled: true,
    testGenerator: function(relativePath, passed, errors) {
      if (errors) {
        errors = "\\n" + this.escapeErrorString(errors);
      } else {
        errors = "";
      }

      return "describe('JSCS - " + relativePath + "', function(){\n" +
        "it('should pass jscs', function() { \n" +
        "  expect(" + !!passed + ", '" + relativePath + " should pass jscs." + errors + "').to.be.ok; \n" +
        "})});\n";
    }
  }
});
```

Maybe there could be a test framework option that defaults to Qunit. Then we could select an appropriate `testGenerator` function based on that option.

**Comment by kellyselden** [comment]
I would be open to this. Since we already depend on QUnit for tests, it doesn't make sense to exclude others.

**Comment by weinberg** [comment]
Here is a modified version of the above script for anyone else attempting to do this in the meantime. It seems the `testGenerator` function signature must have changed.

````javascript
var app = new EmberApp({
  jscsOptions: {
    testGenerator: function(relativePath, errors) {
      var passed;
      if (errors) {
        passed = false;
        errors = "\\n" + this.escapeErrorString(errors);
      } else {
        passed = true;
        errors = "";
      }

      return "describe('JSCS - " + relativePath + "', function(){\n" +
        "it('should pass JSCS', function() { \n" +
        "  expect(" + !!passed + ", '" + relativePath + " should pass jscs. Errors:" + errors + "').to.be.ok; \n" +
        "})});\n";
    }
  }
});````

**Comment by elbeezy** [comment]
+1 to this solution. Using it via `ember-suave` and works out of the box. Would love to see a friendlier approach, though.

**Comment by ronco** [comment]
I'd like to take a crack at adding the suggested test framework config option.

However before starting I can't get the tests to run successfully.  You can see the test failures on my [travis](https://travis-ci.org/ronco/broccoli-jscs).  That's a fresh new branch off of master with no changes as of yet.  Anyone have an idea why it's seemingly caught in a recursive loop when building the tree?  Locally the error is `ENAMETOOLONG`, but it appears to be same underlying cause.

**Comment by kellyselden** [comment]
@ronco That's interesting. I ran the tests locally and they pass. What happens when you run locally?

**Comment by ronco** [comment]
All of the failing tests locally have this same style error:
```
  1) broccoli-jscs options doesn't run if disabled:
     ENAMETOOLONG, name too long '/Users/ronco/github/broccoli-jscs/tests/fixtures/issue-found/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/cache_path-5vfxlj3X.tmp'
  Error: ENAMETOOLONG, name too long 'tests/fixtures/issue-found/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/input_base_path-EkOaRPyC.tmp/0/tmp/cache_path-5vfxlj3X.tmp'
      at Error (native)
      at Object.fs.statSync (fs.js:797:18)
      at getStat (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:108:15)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:70:17)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at _walkSync (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:76:32)
      at Function.entries (node_modules/broccoli-persistent-filter/node_modules/walk-sync/index.js:47:10)
      at Filter.build (node_modules/broccoli-persistent-filter/index.js:65:26)
      at node_modules/broccoli-persistent-filter/node_modules/broccoli-plugin/read_compat.js:61:34
      at lib$rsvp$$internal$$tryCatch (node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:493:16)
      at lib$rsvp$$internal$$invokeCallback (node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:505:17)
      at lib$rsvp$$internal$$publish (node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:476:11)
      at lib$rsvp$asap$$flush (node_modules/broccoli-persistent-filter/node_modules/rsvp/dist/rsvp.js:1198:9)
```

I figure it has to be an npm dependency change.  `rimraf` and `glob` dependencies for `broccoli-persistent-filter` have bumped up in the last month (from 2.4.4 -> 2.5.0 and 5.0.15 -> 6.0.2 respectively).  No CHANGELOG on either of those modules so that's just a shot in the dark.

**Comment by kellyselden** [comment]
@ronco Ah ok. I deleted my node_modules to get the latest versions, now my tests won't pass either.
